In [1]:
import pandas as pd

In [2]:
FILE_PATH: str = "./resources/output/result_llm_2.xlsx"
df: pd.DataFrame = pd.read_excel(FILE_PATH)
df.head()

,Concepto,concepto_cleared,categoria,alg,explicacion
0,COSTO DIRECTO DE OBRA,costo directo obra,Contratos de construcción y urbanización,KEYWORD,NaN
1,ADMINISTRACION (22%),administracion,Servicios Generales,gemini-3.1-flash-lite-preview,Concepto genérico sin descripción suficiente d...
2,IMPROVISTOS (3%),improvistos,Servicios Generales,gemini-3.1-flash-lite-preview,Concepto contable genérico sin actividad defin...
3,"UTILIDAD (4,2016806722%) MAS IVA 19%",utilidad mas iva,Servicios Generales,gemini-3.1-flash-lite-preview,Componente de un contrato sin detalle de la ac...
4,ESTUDIOS Y DISEÑOS MAS IVA 19%,estudios diseños mas iva,Consultoría General/Administración Delegada (PJ),gemini-3.1-flash-lite-preview,Los estudios y diseños corresponden a labores ...

In [ ]:
categorias_validas: list[str] = [
    "Compras Generales",
    "Productos agrícolas/pecuarios (sin proceso industrial)",
    "Café Pergamino o Cereza",
    "Combustibles derivados del petróleo",
    "Vehículos (Adquisición)",
    "Bienes Raíces",
    "Bienes Raíces (Uso diferente a vivienda)",
    "Compra de Oro (por Sociedades de Comercialización Int.)",
    "Servicios Generales",
    "Hoteles, restaurantes y alojamiento",
    "Transporte de Carga (Terrestre, Aéreo o Marítimo)",
    "Transporte de Pasajeros (Terrestre)",
    "Transporte de Pasajeros (Aéreo o Marítimo)",
    "Servicios de Salud",
    "Empresas de Servicios Temporales",
    "Vigilancia y Aseo",
    "Servicios de Sísmica",
    "Honorarios y Comisiones",
    "Interventoría/Consultoría Ingeniería (Infraestructura)",
    "Consultoría General/Administración Delegada (PJ)",
    "Consultoría de Obras Públicas (Factor Multiplicador)",
    "Licencia/Derecho de Uso de Software",
    "Arrendamiento de bienes muebles",
    "Arrendamiento de bienes inmuebles",
    "Contratos de construcción y urbanización",
    "Loterías, Rifas y Apuestas",
    "Colocación independiente de juegos de suerte y azar",
    "Rendimientos financieros (generales)",
    "Rendimientos Financieros (Títulos de Renta Fija/CDT)",
    "Enajenación de activos fijos",
    "Emolumentos Eclesiásticos",
    "Reembolso",
    "Cuota de admon",
    "CONCEPTO VACIO"
]
dict_repair: dict[str, str] = {
    "DESCONOCIDO": "REVISION MANUAL",
    "Transporte de Carga": "Transporte de Carga (Terrestre, Aéreo o Marítimo)",
    'Transporte de Carga (Terrestre, Aereo o Maritimo)': "Transporte de Carga (Terrestre, Aéreo o Marítimo)",
    "Consultoria General/Administracion Delegada (PJ)": "Consultoría General/Administración Delegada (PJ)",
    "Interventoria/Consultoria Ingenieria (Infraestructura)": "Interventoría/Consultoría Ingeniería (Infraestructura)",
    "Transporte de Carga (Terrestre, A3reo o Mar3timo)": "Transporte de Carga (Terrestre, Aéreo o Marítimo)",
    "Contratos de construccion y urbanizacion": "Contratos de construcción y urbanización",
    "Contratos de construcci&oacute;n y urbanizaci&oacute;n": "Contratos de construcción y urbanización",
    "Interventoria/Consultoria Ingeniería (Infraestructura)": "Interventoría/Consultoría Ingeniería (Infraestructura)",
    "Transporte de Pasajeros (Aereo o Maritimo)": "Transporte de Pasajeros (Aéreo o Marítimo)",
    "Contratos de construccin y urbanizacin": "Contratos de construcción y urbanización",
    "Transporte de Pasajeros (A%e9reo o Mar%edtimo)": "Transporte de Pasajeros (Aéreo o Marítimo)",
    "Consultor%eda General/Administraci%f3n Delegada (PJ)": "Consultoría General/Administración Delegada (PJ)",
    "DESCONOCIDO - No se logra entender o definir el concepto al que pertenece": "REVISION MANUAL",
    "Interventor%eda/Consultor%eda Ingenier%eda (Infraestructura)": "Interventoría/Consultoría Ingeniería (Infraestructura)",
    "Interventoría/Consultoría Ingeniería (Infraessential)": "Interventoría/Consultoría Ingeniería (Infraestructura)",
    "Interventoría/Consultoría Ingeniería (Infraexistence)": "Interventoría/Consultoría Ingeniería (Infraestructura)"
}
categorias_erradas: list[str] = [c for c in df["categoria"].drop_duplicates().to_list() if c not in categorias_validas]
categorias_erradas

['DESCONOCIDO',
 'Transporte de Carga',
 'Transporte de Carga (Terrestre, Aereo o Maritimo)',
 'Consultoria General/Administracion Delegada (PJ)',
 'Interventoria/Consultoria Ingenieria (Infraestructura)',
 'Transporte de Carga (Terrestre, A3reo o Mar3timo)',
 'Contratos de construccion y urbanizacion',
 'Contratos de construcci&oacute;n y urbanizaci&oacute;n',
 'Interventoria/Consultoria Ingeniería (Infraestructura)',
 'Transporte de Pasajeros (Aereo o Maritimo)',
 'Contratos de construccin y urbanizacin',
 'Transporte de Pasajeros (A%e9reo o Mar%edtimo)',
 'Consultor%eda General/Administraci%f3n Delegada (PJ)',
 'DESCONOCIDO - No se logra entender o definir el concepto al que pertenece',
 'Interventor%eda/Consultor%eda Ingenier%eda (Infraestructura)',
 'Interventoría/Consultoría Ingeniería (Infraessential)',
 'Interventoría/Consultoría Ingeniería (Infraexistence)']

In [ ]:
def repair_category(category: str) -> str:
    if category in categorias_validas:
        return category
    if category in dict_repair:
        return dict_repair[category]
    return "INVALIDO"

df["categoria"] = df["categoria"].apply(repair_category)
df.head()

,Concepto,concepto_cleared,categoria,alg,explicacion
0,COSTO DIRECTO DE OBRA,costo directo obra,Contratos de construcción y urbanización,KEYWORD,NaN
1,ADMINISTRACION (22%),administracion,Servicios Generales,gemini-3.1-flash-lite-preview,Concepto genérico sin descripción suficiente d...
2,IMPROVISTOS (3%),improvistos,Servicios Generales,gemini-3.1-flash-lite-preview,Concepto contable genérico sin actividad defin...
3,"UTILIDAD (4,2016806722%) MAS IVA 19%",utilidad mas iva,Servicios Generales,gemini-3.1-flash-lite-preview,Componente de un contrato sin detalle de la ac...
4,ESTUDIOS Y DISEÑOS MAS IVA 19%,estudios diseños mas iva,Consultoría General/Administración Delegada (PJ),gemini-3.1-flash-lite-preview,Los estudios y diseños corresponden a labores ...

In [10]:
categorias_erradas: list[str] = [c for c in df["categoria"].drop_duplicates().to_list() if c not in categorias_validas]
categorias_erradas

['REVISION MANUAL']

In [11]:
df.to_excel("./resources/output/conceptos_clasiflicados.xlsx", index=False)